services:
  web:
    build:
      context: ./infra
      dockerfile: Dockerfile.web
    container_name: saas_web
    ports:
      - "8080:80"
    volumes:
      - ./platform-backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: saas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: saasdb
      MYSQL_USER: saasuser
      MYSQL_PASSWORD: saaspass1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: saas_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root1234
    ports:
      - "8081:80"

volumes:
  mysql_data:
